spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${DATASOURCE_USERNAME:system}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true