POST {{DEMO_URL}}/api/events
Content-Type: application/json

{
  "data": {
    "name": "John Doe",
    "age": 30,
    "addresses": [
      {
        "default": true,
        "street": "123 Main St",
        "city": "Anytown",
        "country": {
          "name": "CountryName",
          "code": "CN"
        }
      },
      {
        "street": "123 Main St",
        "city": "Anytown",
        "country": {
          "name": "CountryName",
          "code": "CN"
        }
      }
    ],
    "contact": {
      "email": "john.doe@example.com",
      "phone": "123-456-7890"
    },
    "createdAt": "2023-10-01T12:00:00Z"
  }
}

> {%
    client.global.set("EVENT_ID", null);
    client.global.set("EVENT_ID", response.body.id);
%}

###

GET http://localhost:8080/api/events/{{EVENT_ID}}

###

GET http://localhost:8080/api/events/5108DBAF-B2F1-4EB3-8C0F-2EDF48C95B1C


